name: dispatch target files updated
on:
  push:
    branches:
      - main
    paths:
      - 'test/sources_files'
jobs:
  dispatch-target-updated:
    strategy:
      matrix:
        repo: ['KosukeKokubun/sync_copy_repo']
    name: dispatch-target-updated
    runs-on: ubuntu-latest
    steps:
      - name: dispatch target-updated
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: target-updated